[package]
name = "rs-ecs"
description = "reasonably simple entity component system"
version = "0.2.7"
edition = "2018"
authors = ["Adam Reichold <adam.reichold@t-online.de>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/adamreichold/rs-ecs"

[profile.bench]
debug = true
lto = true
codegen-units = 1
